name: Docker test

on:
  schedule:
    # We want to run it every day
    - cron:  '*/5 * * * *'

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    services:
      ftpserver:
        image: ftpserver/ftpserver
        ports:
          - 2121:2121

    steps:
      - name: Run sample
        env:
          SERVER_PORT: 2121
        run: |
          set -xe
          whoami
          sudo apt-get update
          sudo apt-get install netcat ncftp wget -y
          wget -O file.bin https://github.com/fclairamb/ftpserver/releases/download/v0.5/ftpserver-linux-amd64
          while ! nc -z localhost ${SERVER_PORT} </dev/null; do sleep 1; done
          ncftp ftp://test:test@localhost:${SERVER_PORT} <<EOF
            put -z file.bin remote.bin
            get remote.bin
            quit
          EOF
          if [ ! -f remote.bin ]; then
            exit 1
          fi
